### ISSUE TITLE
Error in method: Run, error code: -2147467262 Assembly Version: 1.0.0.0

### ISSUE THREAD

**Issue by TBye101** [SneakyTactician/CommandEverything#1]
**Exception**
Error code: -2147467262
Error message: Specified cast is not valid.
Method: Run
Source: CommandEverything

**Stack trace**
   at CommandEverything.Framework.Commands.ExitCommand.Run(String Input) in C:\Users\Sneak_000\Source\Repos\CommandEverything\CommandEverything\CommandEverything\Framework\Commands\ExitCommand.cs:line 41
   at CommandEverything.Framework.CommandInterpreter.RecieveInput(String Input) in C:\Users\Sneak_000\Source\Repos\CommandEverything\CommandEverything\CommandEverything\Framework\CommandInterpreter.cs:line 42
   at CommandEverything.Loop.Main(String[] args) in C:\Users\Sneak_000\Source\Repos\CommandEverything\CommandEverything\CommandEverything\Loop.cs:line 25

Type: System.InvalidCastException
System information:
Is 64 bit OS: True
Is 64 bit process: False
OS version: Microsoft Windows NT 6.2.9200.0
Processor count: 8
System page size: 4096
Common Language Runtime version: 4.0.30319.42000

Some Card Games application information: 
Handles: 343
Non paged system memory: 25136
Paged memory: 17719296
Max memory usage: 25460736
Is responding: True
Threads running: 14
Screen Size: {X=0,Y=0,Width=2560,Height=1440}

**Comment by TBye101** [comment]
Just a test.
